### ISSUE TITLE
Doesn't seem to work with React 17

### ISSUE THREAD

**Issue by james-beston** [Taelkir/react-address-lookup#18]
When I went to install this with a Next.js 11 test site I got the following NPM message:

`npm ERR! code ERESOLVE`
`npm ERR! ERESOLVE unable to resolve dependency tree`
`npm ERR! `
`npm ERR! While resolving: xxxxxxxx@0.1.0`
`npm ERR! Found: react@17.0.2`
`npm ERR! node_modules/react`
`npm ERR!   react@"^17.0.2" from the root project`
`npm ERR!` 
`npm ERR! Could not resolve dependency:`
`npm ERR! peer react@"^16.8.6" from react-address-lookup@1.1.1`
`npm ERR! node_modules/react-address-lookup`
`npm ERR!   react-address-lookup@"*" from the root project`
`npm ERR! `
`npm ERR! Fix the upstream dependency conflict, or retry`
`npm ERR! this command with --force, or --legacy-peer-deps`
`npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by Taelkir** [comment]
Agreed, needs updating. Shouldn't be too hard though, I don't imagine it relies on anything that would have been removed with React 17.

**Comment by Taelkir** [comment]
Done! Only took 9 months. :) 

Have updated the npm package to v2.0.0

Will upgrade to React 18 at some point after Storybook updates to support it.
